- name: generate zookeeper default env file
  sudo: yes
  template:
    src: zookeeper-env.j2 
    dest: "/etc/default/{{zookeeper_service}}"
  notify: 
    - restart zookeeper
  tags: 
    - zookeeper
    - zookeeper-docker-create-default-env

- name: generate zookeeper systemd service file 
  sudo: yes
  template:
    src: zookeeper-service.j2 
    dest: "/usr/lib/systemd/system/{{zookeeper_service}}.service"
  notify: 
    - register zookeeper service with systemd 
    - reload systemd daemon 
  tags: 
    - zookeeper
    - zookeeper-docker-create-systemd-sevice
