---
- include: playbooks/provision-hosts.yml

- hosts: all
  roles:
    - { role: common, tags: common }
    - { role: docker, tags: docker }
    - { role: logspout, tags: logspout }

- hosts: dc1:&consul_clients
  roles:
    - { role: consul, tags: consul }

- hosts: dc2:&consul_clients
  roles:
    - { role: consul, tags: consul }

- hosts: dc1:&consul_servers
  serial: 1
  roles:
    - { role: consul, tags: consul }

- hosts: dc2:&consul_servers
  serial: 1
  roles:
    - { role: consul, tags: consul }

- include: playbooks/consul-join-wan.yml

- hosts: all
  gather_facts: no
  roles:
    - { role: registrator, tags: registrator }

- hosts: app_servers
  gather_facts: no
  roles:
    - { role: hello-world, tags: app }

- hosts: load_balancers
  gather_facts: no
  roles:
    - { role: nginx, tags: lb }
