---
- name: run hello-world container
  sudo: yes
  docker:
    name: hello-world
    image: keithchambers/docker-hello-world:latest
    ports: 80
    env: 
      SERVICE_80_NAME: app
      SERVICE_80_CHECK_HTTP: .
      SERVICE_80_CHECK_INTERVAL: 15s
    state: running
