---
- name: run Mesos follower
  docker:
    hostname: "{{ inventory_hostname }}"
    image: "{{ mesos_docker_image }}:{{ mesos_docker_tag }}"
    name: "{{ mesos_follower_docker_name }}"
    env:
      MESOS_PORT: 5051
      MESOS_LOG_DIR: "{{ mesos_log_dir }}"
      MESOS_MASTER: "zk://{% for zk in groups.zookeeper_servers %}{{ hostvars[zk].ansible_default_ipv4.address }}:2181{% if not loop.last %},{% endif %}{% endfor %}/mesos"
      MESOS_CONTAINERIZERS: docker,mesos
      # MESOS_DOCKER: /usr/bin/docker
      # TODO: MESOS_ATTRIBUTES
    state: running
    volumes_from: "{{ mesos_data_volume_name }}"
    volumes:
      - "{{ mesos_log_dir }}:{{ mesos_log_dir }}"
      - "/sys:/sys"
      - "/usr/bin/docker:/usr/local/bin/docker"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/lib64/libdevmapper.so.1.02:/usr/lib/libdevmapper.so.1.02"
    net: host
    privileged: yes
    command: mesos-slave
  tags: mesos,mesos-run-follower-image
