---
- name: create Mesos leader volume
  docker:
    name=mesos-data-volume
    image=tianon/true
    state=present
    volumes={{ mesos_log_dir }},{{ mesos_work_dir }}
  tags: mesos,mesos-leader-docker-data-volume

- name: run Mesos leader
  sudo: yes
  docker:
    hostname: "{{ inventory_hostname }}"
    image: "{{ mesos_docker_image }}:{{ mesos_docker_tag }}"
    name: "{{ mesos_leader_docker_name }}"
    env:
      MESOS_PORT: 5050
      MESOS_HOSTNAME: "{{ ansible_default_ipv4.address }}"
      MESOS_LOG_DIR: "{{ mesos_log_dir }}"
      MESOS_WORK_DIR: "{{ mesos_work_dir }}"
      # TODO: use consul DNS
      MESOS_ZK: "zk://{% for zk in groups.zookeeper_servers %}{{ hostvars[zk].ansible_default_ipv4.address }}:2181{% if not loop.last %},{% endif %}{% endfor %}/mesos"
      # TODO: really this should be // 2 + 1 but Mesos won't start up with 3 nodes that way. Weird.
      MESOS_QUORUM: "{{ groups.mesos_leaders|count // 2 }}"
      SERVICE_5050_NAME: "{{ mesos_leader_docker_name }}"
      SERVICE_TAG: "mesos"
    ports: 5050:5050
    state: running
    volumes_from: mesos-data-volume
    volumes:
      - "{{ mesos_log_dir }}:{{ mesos_log_dir }}"
      - "{{ mesos_work_dir }}:{{ mesos_work_dir }}"
    net: host
    command: mesos-master
  tags: mesos,mesos-run-leader-image
