---
- name: run registrator container
  sudo: yes
  docker:
    name: registrator
    image: progrium/registrator:latest
    state: running
    hostname: "{{ inventory_hostname }}"
    volumes: /var/run/docker.sock:/tmp/docker.sock
    privileged: yes
    links: consul:consul
    command: consul://consul:8500
