
- name: install dnsmasq
  sudo: yes
  yum: 
    name: dnsmasq 
    state: latest
  tags: 
    - dnsmasq
    - dnsmasq-install-package

- name: configure dnsmasq consul lookups
  sudo: yes
  copy: 
    content: 'server=/consul/127.0.0.1#8600'
    dest: /etc/dnsmasq.d/10-consul
  notify:
    - restart dnsmasq
  tags: 
    - dnsmasq
    - dnsmasq-consul
