---
- hosts: localhost
  connection: local
  vars:
    - img_url: http://buildlogs.centos.org/rolling/7/CentOS-7-x86_64-GenericCloud-20141029_01.qcow2
    - img_sha256sum: ea37e583c25927e98c1b75432be72b1bda9b8891b478d32849d2ef3467f24c31
    - img_file: "{{ img_url | basename }}"
    - img_name: "{{ img_file.split('.') | first }}"
    - img_type: "{{ img_file.split('.') | last }}"
    - img_temp: "{{ ansible_env.HOME }}/image_tmp"
  tasks:
    - name: enable epel repo
      sudo: yes
      yum:
        name: epel-release
        state: latest
        
    - name: enable openstack repo
      sudo: yes
      yum:
        name: https://repos.fedorapeople.org/repos/openstack/openstack-icehouse/rdo-release-icehouse-4.noarch.rpm
        state: present

    - name: install qemu-img and python-glanceclient
      sudo: yes
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - qemu-img
        - python-glanceclient

    - name: create img_temp directory
      file:
        path: "{{ img_temp }}"
        state: directory

    - name: download image from url
      get_url:
        url: "{{ img_url }}"
        dest: "{{ img_temp }}/{{ img_file }}"
        sha256sum: "{{ img_sha256sum }}"

    - name: convert image to raw format
      command: >
        qemu-img convert
        "{{ img_temp }}/{{ img_file }}"
        "{{ img_temp }}/{{ img_name }}.raw"
        creates: "{{ img_temp }}/{{ img_name }}.raw"

    - name: upload image to glance
      glance_image:
        auth_url: "{{ os_auth_url }}"
        login_username: "{{ lookup('env','OS_USERNAME') }}"
        login_password: "{{ lookup('env','OS_PASSWORD') }}"
        login_tenant_name: "{{ os_tenant_name }}"
        name: "{{ img_name }}"
        file: "{{ img_temp }}/{{ img_name }}.raw"
        disk_format: raw
        is_public: false
        timeout: 1800
        state: present
